import type { MiddlewareHandler } from "hono";

/**
 * Same policy the SPA needs anyway: everything (script, style, fonts,
 * images) is self-hosted (see web/public/_headers's matching copy for the
 * static-asset half of this — Workers doesn't apply that file to responses
 * generated by the Worker itself, so the policy has to be declared twice,
 * once per response path). `data:` is allowed for img-src only because
 * some inline SVG icons are still authored as data URIs; nothing else in
 * the bundle needs it.
 */
// challenges.cloudflare.com is the Turnstile bot-check widget on the
// signup form (see src/turnstile.ts) — same vendor as everything else this
// product already trusts (Cloudflare itself hosts the Worker, D1, and
// static assets), not a third party pulled in casually. It needs its own
// script (widget JS), its own frame (the actual challenge iframe), and its
// own connect-src (the widget's background verification calls).
// Paddle.js (the Pro upgrade checkout, see web/src/pages/Dashboard.tsx) is
// the second third party trusted here, same "same vendor as everything
// else" bar as Turnstile: cdn.paddle.com is Paddle's own documented-required
// load path (developer.paddle.com/paddlejs/include-paddlejs, fetched
// 2026-07-24 — "you must only load Paddle.js directly from
// https://cdn.paddle.com/"). The checkout overlay itself and its background
// calls span several Paddle-owned subdomains (buy.paddle.com,
// sandbox-buy.paddle.com, checkout-service.paddle.com, and others) that
// Paddle does not publish as a fixed, exhaustive list — https://*.paddle.com
// is used for connect-src/frame-src rather than guessing at an incomplete
// enumeration that could silently break checkout later. Verified against
// a real live browser console (2026-07-24, real sandbox checkout attempt),
// which caught two real gaps: (1) Paddle.js loads its OWN stylesheet from
// {sandbox-,}cdn.paddle.com/paddle/v2/assets/css/paddle.css, needing the
// same allowance as script-src; (2) the checkout overlay's actual layout
// (its styled-components classes, confirmed via a live element inspection
// that found `position` missing from computed styles entirely — silently
// defaulting to `static` instead of the fixed full-screen overlay it's
// supposed to be) is injected as inline <style> tags at runtime, which
// CSP blocks by default regardless of style-src's URL allowlist — that
// needs 'unsafe-inline' specifically. Scoped to style-src only, not
// script-src: inline CSS injection can't execute JavaScript, so this
// doesn't reopen the XSS surface 'unsafe-inline' would on scripts.
const CSP = [
  "default-src 'self'",
  "script-src 'self' https://challenges.cloudflare.com https://cdn.paddle.com",
  "style-src 'self' 'unsafe-inline' https://*.paddle.com",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self' https://challenges.cloudflare.com https://*.paddle.com",
  "frame-src https://challenges.cloudflare.com https://*.paddle.com",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
  "upgrade-insecure-requests",
].join("; ");

/**
 * Response headers a browser-facing service is expected to send in
 * 2026 and didn't — verified via `curl -sI` against production, which
 * returned none of these. Applied to every Worker-generated response
 * (/api/*, /ping/*, /health); the static SPA shell/JS/CSS/assets are
 * served directly by Cloudflare's static-assets layer and never reach
 * this middleware, so they get the same policy from web/public/_headers
 * instead.
 *
 * 180-day HSTS with includeSubDomains but deliberately no `preload`:
 * preload-list submission is a near-irreversible commitment (removal
 * takes months and requires every current and future subdomain to serve
 * valid HTTPS forever) made without visibility into every subdomain this
 * domain might ever use — 180 days already gives strong protection
 * without that one-way door.
 */
export function securityHeaders(): MiddlewareHandler {
  return async (c, next) => {
    await next();
    c.header("X-Content-Type-Options", "nosniff");
    c.header("X-Frame-Options", "DENY");
    c.header("Referrer-Policy", "strict-origin-when-cross-origin");
    c.header(
      "Permissions-Policy",
      "geolocation=(), camera=(), microphone=(), payment=(), usb=(), interest-cohort=()",
    );
    c.header("Content-Security-Policy", CSP);
    c.header("Strict-Transport-Security", "max-age=15552000; includeSubDomains");
    // Every response here is either session/API-key-authenticated and
    // user-specific, or a mutation — neither should ever be reused from a
    // shared cache (browser or Cloudflare edge). No Cache-Control was being
    // sent at all before this, which is the kind of gap that's invisible
    // until two different users' responses get conflated by an intermediary
    // cache; cheap to close outright rather than reason about case by case.
    c.header("Cache-Control", "private, no-store");
  };
}
